//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daily_Accountant_Api
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Daily_Accountant_DbEntities : DbContext
    {
        public Daily_Accountant_DbEntities()
            : base("name=Daily_Accountant_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ExpensesDetail> ExpensesDetails { get; set; }
        public virtual DbSet<InvestmentDetail> InvestmentDetails { get; set; }
        public virtual DbSet<InvestmentNameId> InvestmentNameIds { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WalletDetail> WalletDetails { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
    }
}
