//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daily_Accountant_Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesDetail
    {
        public int Expenses_Id { get; set; }
        public int registerId { get; set; }
        public System.DateTime date { get; set; }
        public string NOte { get; set; }
        public long Amount { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
