//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daily_Accountant_Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestmentNameId
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvestmentNameId()
        {
            this.InvestmentDetails = new HashSet<InvestmentDetail>();
        }
    
        public int Id { get; set; }
        public string Investment_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestmentDetail> InvestmentDetails { get; set; }
    }
}
