// <auto-generated />
namespace Daily_Accountant_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class userregisterform : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userregisterform));
        
        string IMigrationMetadata.Id
        {
            get { return "202005080415388_userregisterform"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
